diff a/cvi_mpi/modules/isp/cv181x/isp-tool-daemon/isp_daemon_tool/Makefile b/cvi_mpi/modules/isp/cv181x/isp-tool-daemon/isp_daemon_tool/Makefile	(rejected hunks)
@@ -1,6 +1,6 @@
 SHELL = /bin/bash
 ifeq ($(PARAM_FILE), )
-	PARAM_FILE:=../../../../Makefile.param
+	PARAM_FILE:=../../../../../Makefile.param
 	include $(PARAM_FILE)
 endif
 
