#!/bin/sh

if [ "$1" = "start" ]
then
	. /etc/profile
	if [ -e "/etc/run_usb.sh" ] ; then

		export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/system/lib
		export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64v0p7_xthead/lp64d

		#host
		#echo host > /proc/cviusb/otg_role

		#rndis
		/etc/run_usb.sh probe rndis
		echo "root" | su -c '/etc/run_usb.sh start' root
		ifconfig usb0 up

		#adb
		#/etc/run_usb.sh probe adb
		#echo "root" | su -c '/etc/run_usb.sh start' root
	fi
fi
