#!/bin/sh

if [ "${1}" = start ]
then
	prefix=lubancat
	if [ -e /boot/hostname.prefix ]
	then
		prefix=$(cat /boot/hostname.prefix)
	fi
	old_hostname=$(cat /etc/hostname)
	#new_hostname=${prefix}-$(sha512sum /sys/class/cvi-base/base_uid | head -c 4)
	new_hostname=${prefix}

	if [ -e /boot/hostname ]
	then
		new_hostname=$(cat /boot/hostname)
	fi

	if [ "${old_hostname}" != "${new_hostname}" ]
	then
		hostname ${new_hostname}
		echo ${new_hostname} > /etc/hostname
		sed -i -e "s/${old_hostname}/${new_hostname}/g" /etc/hosts
	fi
	echo "hostname: ${new_hostname}"
fi
