#!/bin/sh

. /etc/profile

start() {
	if ifconfig usb0 > /dev/null 2>&1; then
		if [ ! -e /boot/boot_mac_usb0 ]
		then
			mac_address_rndis=$(ifconfig usb0 | grep HWaddr | awk '{print $5}')
			echo "$mac_address_rndis" > /boot/boot_mac_usb0
		else
			ifconfig usb0 down
			mac_address_rndis=$(cat /boot/boot_mac_usb0)
			ifconfig usb0 hw ether $mac_address_rndis
		fi
		ifconfig usb0 192.168.137.10 up
		route add default gw 192.168.137.1 metric 800
	fi
}

if [ "${1}" = "start" ]
then
	start
fi
