#!/bin/sh

. /etc/profile

if [ "${1}" = start ]
then
	if [ ! -e "/boot/boot_init" ] ; then
		ROOT_PART=$(cat /proc/cmdline | sed 's/ /\n/g' | grep root= | awk -F 'root=' '{print $2}'| awk -F '/' '{print $3}')

		ROOT_DEV=${ROOT_PART%p*}

		PART_NUM=${ROOT_PART#${ROOT_DEV}p}

		LAST_PART_NUM=$(parted /dev/${ROOT_DEV} -ms unit s p | tail -n 1 | cut -f 1 -d:)
		
	if [ $LAST_PART_NUM -ne $PART_NUM ]; then
		echo "$ROOT_PART is not the last partition. Don't know how to expand"
	fi

		#/*******************sd启动boot分区设置自动挂载*******************/
		if blkid | grep -q "/dev/${ROOT_DEV}p1"; then
			if ! grep -q "${ROOT_DEV}p1" /etc/fstab ; then
				echo "/dev/${ROOT_DEV}p1  /boot  auto  defaults  0 2" >> /etc/fstab
			fi
			mkdir -p /boot
			mount /dev/${ROOT_DEV}p1 /boot
		else    
			#/*******************emmc启动usr data分区先进行格式化再设置自动挂载*******************/
			if ! grep -q "${ROOT_DEV}p7" /etc/fstab ; then
				mkfs.ext4 "/dev/${ROOT_DEV}p7"
				echo "/dev/${ROOT_DEV}p7  /mnt/data  auto  defaults  0 2" >> /etc/fstab
				mkdir -p /mnt/data
				mount /dev/${ROOT_DEV}p7 /mnt/data
			fi
		fi

		#/*******************扩容*******************/
		if [ ! -e "/boot/boot_dilatation_init" ] ; then
			if blkid | grep -q "boot"; then
				parted  /dev/${ROOT_DEV} <<EOF
unit GB print
resizepart ${LAST_PART_NUM}
-1
yes
quit
EOF
			fi
		resize2fs /dev/$ROOT_PART
		touch /boot/boot_dilatation_init
		fi

		touch /boot/boot_init
	fi
fi
