diff a/osdrv/Makefile b/osdrv/Makefile	(rejected hunks)
@@ -61,11 +61,11 @@ ifeq ($(CHIP_ARCH), $(filter $(CHIP_ARCH), CV183X CV182X))
 endif
 
 ifeq ($(CVIARCH), $(filter $(CVIARCH), CV181X))
-	KO_LIST += sys vi snsr_i2c cif vpss dwa rgn vo rtos_cmdqu fast_image cvi_vc_drv ive
+	KO_LIST += sys vi snsr_i2c cif vpss dwa rgn vo rtos_cmdqu fast_image cvi_vc_drv ive #motor
 	BASE_DEP = sys
 	FB_DEP = vpss
 else ifeq ($(CVIARCH), $(filter $(CVIARCH), CV180X))
-	KO_LIST += sys vi snsr_i2c cif vpss dwa rgn rtos_cmdqu fast_image cvi_vc_drv
+	KO_LIST += sys vi snsr_i2c cif vpss dwa rgn rtos_cmdqu fast_image cvi_vc_drv #motor
 	BASE_DEP = sys
 	FB_DEP = vpss
 endif
